### ISSUE TITLE
Problem with npm install

### ISSUE THREAD

**Issue by krivochenko** [angular/universal-starter#383]
Hi! I use Windows 10 with Docker Toolbox.

1. I clone with repo;
2. I added docker-compose.yml with following content:

```
version: '2'

services:
    nodejs:
        image: node:7.7.3
        volumes:
            - ./:/var/www/sources
        working_dir: /var/www/sources
        command: "npm install"          
```
3. run `docker-compose up`.

I get warnings:
```
nodejs_1  | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
nodejs_1  | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
nodejs_1  | npm WARN @ngtools/webpack@1.1.9 requires a peer of @angular/compiler-cli@2.2.3 but none was installed.
nodejs_1  | npm WARN @ngtools/webpack@1.1.9 requires a peer of @angular/core@2.2.3 but none was installed.
nodejs_1  | npm info ok
```

What I do wrong? Which information I can also provide? 

Thanks for help!
